# Generated by Django 5.1.4 on 2025-03-12 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 20, 1, 17, 953115, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 20, 1, 17, 952809, tzinfo=datetime.timezone.utc)),
        ),
    ]
