# Generated by Django 5.1.4 on 2025-03-12 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_created_date_alter_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 20, 7, 3, 990476, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 20, 7, 3, 990180, tzinfo=datetime.timezone.utc)),
        ),
    ]
